import { Component, OnInit } from '@angular/core';
import { ActivityModel } from '../../model/activity.model';
import { UserModel } from '../../model/user.model';
import { CustomerModel } from '../../model/customer.model';
import { FormBuilder, FormGroup } from '@angular/forms';
import { ActivityService } from '../../service/activity.service';
import { CustomerService } from '../../service/customer.service';
import { UserService } from '../../service/user.service';
import { Router } from '@angular/router';


@Component({
  selector: 'app-createactivity',
  templateUrl: './createactivity.component.html',
  styleUrl: './createactivity.component.css'
})
export class CreateactivityComponent implements OnInit{

  activity: ActivityModel = new ActivityModel();
  customers: CustomerModel[] = [];
  agents: UserModel[] = [];

  constructor(
    private activityService: ActivityService,
    private customerService: CustomerService,
    private userService: UserService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.loadCustomers();
    this.loadAgents();
  }

  loadCustomers(): void {
    this.customerService.getAllCustomer().subscribe({
      next: (data) => (this.customers = data),
      error: (error) => console.error('Error loading customers:', error),
    });
  }

  loadAgents(): void {
    this.userService.getUsers().subscribe({
      next: (data) => (this.agents = data),
      error: (error) => console.error('Error loading agents:', error),
    });
  }

  createActivity(): void {
    this.activityService.createActivity(this.activity).subscribe({
      next: (response) => {
        console.log('Activity created successfully:', response);
        this.router.navigate(['/viewactivity']); // Navigate to activity list
      },
      error: (error) => {
        console.error('Error creating activity:', error);
      },
    });
  }



  // activityForm!: FormGroup;
  // users: UserModel[] = [];
  // customers: CustomerModel[] = [];
  // activity: ActivityModel = new ActivityModel();

  // constructor(
  //   private fb: FormBuilder,
  //   private userService: UserService,
  //   private customerService: CustomerService,
  //   private activityService: ActivityService,
  //   private router: Router
  // ) {}

  // ngOnInit(): void {
  //   this.initializeForm();
  //   this.loadUsers();
  //   this.loadCustomers();
  // }

  // initializeForm() {
  //   this.activityForm = this.fb.group({
  //     activityType: [''],
  //     activityDate: [''],
  //     description: [''],
  //     customer: [''],
  //     agent: ['']
  //   });
  // }

  // loadUsers() {
  //   this.userService.getUsers().subscribe((data: UserModel[]) => {
  //     this.users = data;
  //   });
  // }

  // loadCustomers() {
  //   this.customerService.getAllCustomer().subscribe((data: CustomerModel[]) => {
  //     this.customers = data;
  //   });
  // }

  // onSubmit() {
  //   if (this.activityForm.valid) {
  //     const selectedCustomer = this.customers.find(
  //       (c) => c.name === this.activityForm.value.customer
  //     );
  //     const selectedUser = this.users.find(
  //       (u) => u.name === this.activityForm.value.agent
  //     );

  //     if (selectedCustomer && selectedUser) {
  //       const newActivity: ActivityModel = {
  //         id: 0, // ID will be generated by the backend
  //         activityType: this.activityForm.value.activityType,
  //         activityDate: this.activityForm.value.activityDate,
  //         description: this.activityForm.value.description,
  //         customer: selectedCustomer,
  //         agent: selectedUser
  //       };

  //       this.activityService.createActivity(newActivity).subscribe(() => {
  //         this.router.navigate(['/viewact']);
  //       });
  //     } else {
  //       alert('Please select valid customer and agent');
  //     }
  //   } else {
  //     alert('Please fill in all fields');
  //   }
  // }




}
